<?xml version="1.0" encoding="UTF-8"?>     
<!DOCTYPE music_library[
    <!ELEMENT music_library (title,artist,country,price,year)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT artist (#PCDATA)>
    <!ELEMENT country (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
]>
<music_library>
    <title>JGFKLSDA</title>
    <artist>DSFSD</artist>
    <country>DFSD</country>
    <price>SDFDS</price>
    <year>DSAFDSAF</year>
</music_library>